name: Create Release
on:
  push:
    tags:
      - 'v*' #Push events to matching v*, i.e. v1.0, v20.15.10'

jobs:
  create_release:
    name: Create Release
    uses: linchpin/actions/.github/workflows/create-release.yml@main
    with:
      themes: '["none"]'
    secrets:
      packagist_auth: ${{ secrets.PACKAGIST_COMPOSER_AUTH_JSON }}
      bot_token: ${{ secrets.GITHUB_TOKEN }}
